S = 0  # Inicial
I = 1  # Identificadores
A = 2  # Asignaciones
T = 3  # Tipos de dato
F = 4  # Finales
E = 5  # Expresiones
B = 6  # Bloque de codigo
C = 7  # Control
EI = 8  # exp if
OL = 9  # Op logico
EL = 10  # ELSE
BU = 11  # Bucles
EF = 12  # Expresiones del for
TI = 13  # tipo de dato
DF = 14  # Declaracion de funciones
ID = 15  # macros y def
OPA = 16 #operadores
AR = 17  # Exp aritmeticas
R=18 #combinaciones de return
EE=19
