S=0 #Inicial
I=1 #Identificadores
A=2 #Asignaciones
T=3 #Tipos de dato 
F=4 #Finales
K=5 #keys
E=6 #Expresiones
AR=7 #Exp aritmeticas
B=8 #Bloque de codigo
C=9 #Control
OL=10 # Op logico
BU=11 #Bucles
FU=12 #funciones
FUI=13 #tipo funciones
TI=13 #tipo de dato
IN=14 #enteros