from utils.Nterminales import *

tablaLL1 = [
    [S, 'int', ['int', I, F]],
    [S, 'char', ['char', I, F]],
    [S, 'float', ['float', I, F]],
    [S, 'void', ['void', I, F]],
    [S, 'identificador', [I, F]],
    [S, 'if', [K]],
    [S, 'llaveder', ['llaveder']],
    [S, 'for', ['for', B]],
    [S, 'while', ['while']],
    [S, 'eof', ['eof']],
    [B, 'parenizq', ['parenizq', E, 'parender', 'llaveizq', S, S]],
    # S seria el bloque de codigo
    [K, 'if', ['if', 'parenizq', E, 'parender',
               'llaveizq', S, 'else', 'llaveizq', S, S]],
    [E, 'identificador', ['identificador', OL, 'identificador']],
    [E, 'int', ['int', 'identificador', 'asignacion', 'number', 'puntocoma',
                'identificador', OL, 'number', 'puntocoma', 'identificador', 'for_or']],
    [OL, 'logico', ['logico']],
    [I, 'identificador', ['identificador', A]],
    [A, 'asignacion', ['asignacion', T]],
    [A, 'coma', [F]],
    [A, 'puntocoma', [F]],
    [A, 'parenizq', ['parenizq', FU, FUI]],  # declaracion de funciones
    [FUI, 'puntocoma', ['puntocoma', S]],
    [FUI, 'llaveizq', ['llaveizq', S, S]],
    [FU, 'int', ['int', FU]],
    [FU, 'float', ['float', FU]],
    [FU, 'identificador', ['identificador',FU]],
    [FU, 'char', ['char', FU]],
    [FU, 'parender', ['parender']],
    [FU, 'coma', ['coma', FU]],
    [T, 'number', ['number']],
    [T, 'double', ['double']],
    [T, 'character', ['character']],
    [F, 'identificador', None],
    [F, 'coma', ['coma', I, F]],
    [F, 'puntocoma', ['puntocoma', S]],
    [F, 'eof', ['eof']]
]
