reservadas={
    'if':'IF',
    'else':'ELSE',
    'using':'USING',
    'return':'RETURN',
    'void':'VOID',
    'int':'INT',
    'string':'STRING',
    'bool':'BOOL',
    'do':'DO',
    'while':'WHILE',
    'for':'FOR'
}