reservadas={
    'if':'keyword',
    'else':'keyword',
    'include':'keyword',
    'iostream':'keyword',
    'using':'keyword',
    'return':'keyword',
    'void':'keyword',
    'int':'keyword',
    'string':'keyword',
    'bool':'keyword',
    'do':'DO',
    'while':'WHILE',
    'for':'FOR'
}