reservadas={
    'class':'palabra_reservada',
    'if':'palabra_reservada',
    'else':'palabra_reservada',
    'using':'palabra_reservada',
    'return':'palabra_reservada',
    'const':'palabra_reservada',
    'int':'palabra_reservada',
    'double':'palabra_reservada',
    'string':'palabra_reservada',
    'bool':'palabra_reservada',
    'for':'palabra_reservada'
}